# Generated by Django 4.2.8 on 2024-03-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_feedback_alter_register_phonenumber'),
        ('module1', '0003_feedback'),
    ]

    operations = [
    ]
